before_script:
  - export CI_DISABLE_CURNN_TEST=true

variables:
  CI_IMAGE_TAG: 'cuda'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/common.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.0.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.1.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_dev.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/coverage_v1.1.yml'

.gpu:
  extends: .test
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - mkdir $JULIA_DEPOT_PATH # Pkg3.jl#325
    - julia --project -e 'using Pkg;
                          Pkg.add("CuArrays");
                          Pkg.add("CUDAnative");
                          Pkg.add("CUDAdrv");
                          Pkg.add("GPUArrays");
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.test(; coverage=true);'

test:v1.0:
  extends: .gpu

test:v1.1:
  extends: .gpu

test:dev:
  extends: .gpu
  allow_failure: true
